### ISSUE TITLE
train data

### ISSUE THREAD

**Issue by qt111111** [kkraoj/lfmc_from_sar#1]
![image](https://user-images.githubusercontent.com/56248051/119261302-6038e100-bc09-11eb-9841-d3f37f1626c3.png)
Hello, what data does this "fmc_28_may_2019" correspond to, and what paths' dir_data',' dir_codes' and' dir_figures' respectively represent

**Comment by kkraoj** [comment]
`fmc_28_may_2019` corresponds to the downloaded file from NFMD. and the various `dir_` commands point to the directories with different information. As per our email conversation, I understand this issue is resolved so I am closing this issue.
